title: Ulyana Piterbarg
url: "https://upiterbarg.github.io"
baseurl: ""

markdown: kramdown

tracking_id: UA-144023591-1

remote_theme: "ankitsultana/researcher@gem"

footer: yes

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://upiterbarg.github.io"
 - name: "Technical Projects"
   link: "projects"
 - name: "CV"
   link: "docs/resume.pdf"
 - name: "Contact"
   link: "contact"

plugins:
 - jekyll-include-cache
